set nocompatible

"配置backspace键工作方式
"set backspace=indent,eol,start
"
""显示行号
set number
"设置在编辑过程中右下角显示光标的行列信息
"set ruler
""当一行文字很长时取消换行
"set nowrap
"
""在状态栏显示正在输入的命令
set showcmd

"设置历史记录条数
"set history=1000
"
""设置取消备份 禁止临时文件生成
set nobackup
set noswapfile

"突出现实当前行列
""set cursorline
"set cursorcolumn
"
""设置匹配模式 类似当输入一个左括号时会匹配相应的那个右括号
set showmatch

"设置C/C++方式自动对齐
"set autoindent
"set cindent
"
""开启语法高亮功能
syntax enable
syntax on

"指定配色方案为256色
"set t_Co=256
"
""设置搜索时忽略大小写
set ignorecase

"设置在Vim中可以使用鼠标 防止在Linux终端下无法拷贝
"" set mouse=a

"设置Tab宽度
"set tabstop=2
""设置自动对齐空格数
set shiftwidth=2
"设置按退格键时可以一次删除4个空格
"set softtabstop=2
""设置按退格键时可以一次删除4个空格
set smarttab
"将Tab键自动转换成空格 真正需要Tab键时使用[Ctrl + V + Tab]
"set expandtab
"
"
""设置编码方式
set encoding=utf-8
"自动判断编码时 依次尝试一下编码
"set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
"
""检测文件类型
filetype on
"针对不同的文件采用不同的缩进方式
"filetype indent on
""允许插件
filetype plugin on
"启动智能补全
"filetype plugin indent on
"
"
""==================================
"    vundle 配置
"    "    :BundleInstall 安装
"    "    :BundleInstall! 更新
"    "    :BundleClean 注释某行之后，执行用来卸载
"    "==================================
"
"    "开始使用Vundle的必须配置
"    set nocompatible
"    filetype off
"    set rtp+=~/.vim/bundle/vundle/
"    call vundle#rc()
"    "
"    ""使用Vundle来管理Vundle
Bundle 'gmarik/vundle'

"PowerLine插件 状态栏增强展示
"Bundle 'Lokaltog/vim-powerline'
""NerdTree能够提供一个目录文件预览窗口，就像众多IDE的文件浏览窗口一样。在vim的命令模式下输入:NerdTree即可调出
Bundle 'scrooloose/nerdtree'
let NERDTreeShowBookmarks=1
autocmd vimenter * NERDTree
map :silent! NERDTreeToggle

"vim有一个状态栏 加上powline则有两个状态栏
"set laststatus=2
"set t_Co=256
"let g:Powline_symbols='fancy'
"
""Vundle配置必须 开启插件
filetype plugin indent on



"=== 主题solarized ===
"Bundle 'altercation/vim-colors-solarized'
"let g:solarized_termcolors=256
"let g:solarized_termtrans=1
"let g:solarized_contrast="normal"
"let g:solarized_visibility="normal"
"
"syntax enable
"set background=light
"colorscheme solarized
"
""=== indentLine代码排版缩进标识 ===
Bundle 'Yggdroot/indentLine'
let g:indentLine_noConcealCursor = 1
let g:indentLine_color_term = 0
"缩进的显示标识|
"let g:indentLine_char = '¦'
"
"
""=== markdown编辑插件 ===
Bundle 'plasticboy/vim-markdown'
"let g:vim_markdown_folding_disabled=1
